### ISSUE TITLE
I2C update

### ISSUE THREAD

**Issue by Euter2** [sim0nx/tsl2561#3]
Library doesn't work with current I2C micropython implementation.
AttributeError: 'I2C' object has no attribute...

**Comment by sim0nx** [comment]
I haven't ever used micropython before but I suspect this is due to its implementation as it is working with the standard python interpreter.

"MicroPython is a lean and efficient implementation of the Python 3 programming language that includes a small subset of the Python standard library" .... from their website.

If you could help with tracking down the issue I would be glad to implement necessary changes.

Closing issue for now
